[DEFAULT]
ROOT_DIR = D:/GenDataCode

[DATASET]
NAME = ETTh2
BASE_DIR = ${ROOT_DIR}/dataProcess/ETT/output/${DATASET:NAME}

[MODEL]
TYPE = timeVAE
CHOICES = vae_dense,vae_conv,timeVAE

[Paths]
# 数据集路径
DATASETS_DIR = ${DATASET:BASE_DIR}/${DATASET:NAME}

# 输出目录 = 数据集 × 模型
OUTPUTS_DIR = ${ROOT_DIR}/model/TimeVAE/output/${DATASET:NAME}/${MODEL:TYPE}

GEN_DATA_DIR = ${OUTPUTS_DIR}/gen_data
MODELS_DIR   = ${OUTPUTS_DIR}/models
TSNE_DIR     = ${OUTPUTS_DIR}/tsne

SRC_DIR = ${ROOT_DIR}/model/TimeVAE/src
CONFIG_DIR = ${SRC_DIR}/config

HYPERPARAMETERS_FILE_PATH = ${CONFIG_DIR}/hyperparameters.yaml
