[Data]
data_name = AirQuality(bj)
z_dim = 1
seq_len = 108

[Model]
model = TimeGAN
module = gru
hidden_dim = 24
num_layer = 1

[Training]
iteration = 5000
batch_size = 32
metric_iteration = 10
isTrain = True
lr = 0.0005
beta1 = 0.9

w_gamma = 1.0
w_es = 0.1
w_e0 = 10.0
w_g = 10.0

print_freq = 500
load_weights = False
resume =
display = False

[System]
workers = 2
device = gpu
gpu_ids = 0
ngpu = 1
outf = output
name = airquality_beijing_timegan
manualseed = 2026

[Visdom]
display_server = http://localhost
display_port = 8097
display_id = 0