[Data]
# 数据集名称
data_name = Traffic

# 数据维度（特征数）

z_dim = 1

# 输入序列长度
seq_len = 96


[Model]
# 模型类型
model = TimeGAN

# RNN 类型（gru / lstm / lstmLN）
module = gru

# 隐藏层维度
hidden_dim = 24

# RNN 层数
num_layer = 3


[Training]
# 训练迭代次数
iteration = 30000

# 批次大小
batch_size = 128

# 计算评估指标的间隔
metric_iteration = 10

# 是否训练
isTrain = True

# 学习率
lr = 0.001

# Adam 优化器 beta1
beta1 = 0.9

# TimeGAN 损失权重
w_gamma = 1.0
w_es = 0.1
w_e0 = 10.0
w_g = 100.0

# 控制台打印频率
print_freq = 1000

# 是否加载预训练权重
load_weights = False

# 恢复训练的 checkpoint 路径
resume =

# 是否使用 Visdom
display = False


[System]
# DataLoader 工作进程
workers = 8

# 设备类型（gpu / cpu）
device = gpu

# GPU ID（多个用逗号）
gpu_ids = 0

# GPU 数量
ngpu = 1

# 输出路径
outf = output

# 实验名称
name = Traffic_timegan

# 随机种子
manualseed = 2026


[Visdom]
display_server = http://localhost
display_port = 8097
display_id = 0
