[data]
seq_len = 96
pred_len = 12
val_ratio = 0.2
test_ratio = 0.2
normalizer = max01
stamp = False
freq = h
condition_dim = 6

[model]
latent_dim = 2
enc_in = 6
dec_in = 6
c_out = 6
d_model = 64
n_heads = 8
num_kernels = 6
d_ff = 32
d_layers = 1
e_layers = 2
column_wise = False
top_k = 5
moving_avg = 25
factor = 3
embed = timeF
dropout = 0.1
timeenc = 1

[train]
loss_func = mae
seed = 12
batch_size = 32
epochs = 200
tf_decay_steps = 2000
lr_init = 0.0001
lr_decay = True
lr_decay_rate = 0.1
lr_decay_step = 10,100,200
early_stop = True
early_stop_patience = 20
grad_norm = False
max_grad_norm = 5
real_value = False
teacher_forcing = False

[test]
mae_thresh = None
mape_thresh = 0.

[log]
log_step = 5
plot = False

